### ISSUE TITLE
安装出错啦！使用docker-compose build 时出现错误

### ISSUE THREAD

**Issue by sang8052** [Zo3i/frpMgr#1]
Centos7 安装此项目，在安装了docker,docker-compose 后
创建数据库时正常
但是在docker 项目的时候出现异常

[root@iZj6c6ohwrcvsiejh7pc9uZ 成品]# docker-compose build
mysql uses an image, skipping
Building frp
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

**Comment by Zo3i** [comment]
可能是你mysql需要自己打包，所以在启动之前需要先进入到 mysql 文件夹中 build mysql 镜像: docker build -t jo/mysql .

**Comment by sang8052** [comment]
thanks , 我打包了mysql 的，没有作用

**Comment by Zo3i** [comment]
我新增了一个一键搭建的脚本，
https://raw.githubusercontent.com/Zo3i/frpMgr/87e69750cd37efde56ae3ede60daf8f5662a01a4/web/src/main/docker/final/run.sh
下载执行bash ./run.sh即可

**Comment by sang8052** [comment]
谢谢 我试试 



------------------ 原始邮件 ------------------
发件人: "Tionsin"<notifications@github.com>; 
发送时间: 2019年5月20日(星期一) 中午1:06
收件人: "Zo3i/frpMgr"<frpMgr@noreply.github.com>; 
抄送: "925040692"<sang8052@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Zo3i/frpMgr] 安装出错啦！使用docker-compose build 时出现错误 (#1)




我新增了一个一键搭建的脚本，
 https://raw.githubusercontent.com/Zo3i/frpMgr/87e69750cd37efde56ae3ede60daf8f5662a01a4/web/src/main/docker/final/run.sh
 下载执行bash ./run.sh即可

**Comment by Zo3i** [comment]
不客气，我发现我的邮件没有提醒，所以回复的这么晚。。
