### ISSUE TITLE
服务器重启后，如何重启服务？

### ISSUE THREAD

**Issue by luisxin** [Zo3i/frpMgr#10]
还请帮忙指明如何启动frp及frpmgr的服务

**Comment by Zo3i** [comment]
Centos7的机器，运行文档中的两行代码即可。另外不要开多个issues。 之前那个我关了。

**Comment by luisxin** [comment]
> Centos7的机器，运行文档中的两行代码即可。另外不要开多个issues。 之前那个我关了。

文档中的两行代码是重装安装啊，我是想要手动启动frpmgr项目。

**Comment by Zo3i** [comment]
你是想本地启动二次开发吗。

**Comment by luisxin** [comment]
> 你是想本地启动二次开发吗。

不是，是因为阿里云服务器使用的是证书登陆，frpmgr后台只能使用密码验证的方式，所以修改了服务器的设置，并需要重启。启动后，访问899/9frp地址，发frpmgr的服务并没有启动，或者说是docker没有启动？没有接触过docker，所以不知道怎么启动项目了。。

**Comment by luisxin** [comment]
![image](https://user-images.githubusercontent.com/16147110/65302373-99f05380-dbad-11e9-94d8-a5fbf06e76d5.png)
![image](https://user-images.githubusercontent.com/16147110/65302384-9fe63480-dbad-11e9-8805-4b1fd631c0e2.png)

**Comment by Zo3i** [comment]
> > 你是想本地启动二次开发吗。
> 
> 不是，是因为阿里云服务器使用的是证书登陆，frpmgr后台只能使用密码验证的方式，所以修改了服务器的设置，并需要重启。启动后，访问899/9frp地址，发frpmgr的服务并没有启动，或者说是docker没有启动？没有接触过docker，所以不知道怎么启动项目了。。

找frpmgr的项目目录。cd ./web/src/main/docker/final  然后执行 docker-compose down 最后执行docker-compose up

**Comment by luisxin** [comment]
回复得好快。已经启动成功了
远程安装 出现404，要怎么办？
![image](https://user-images.githubusercontent.com/16147110/65304022-23098980-dbb2-11e9-810a-54b3bdb2feca.png)

**Comment by Zo3i** [comment]
软件的bug. 稍后我改一个版本上去。

**Comment by Zo3i** [comment]
> 回复得好快。已经启动成功了
> 远程安装 出现404，要怎么办？
> ![image](https://user-images.githubusercontent.com/16147110/65304022-23098980-dbb2-11e9-810a-54b3bdb2feca.png)

Bug已经修复了。你重新部署一下就行了。

**Comment by luisxin** [comment]
不好意思 ，又有新的问题，
在后台可以查看到连接成功，但却依然无法访问。服务器是国内的阿里云，这个会有影响吗？
![image](https://user-images.githubusercontent.com/16147110/65311223-84395900-dbc2-11e9-958f-61d915483b89.png)
![image](https://user-images.githubusercontent.com/16147110/65311278-9adfb000-dbc2-11e9-9ea1-bfcc7ae1604a.png)
![image](https://user-images.githubusercontent.com/16147110/65311298-a16e2780-dbc2-11e9-8c7f-56b06e8d56ec.png)

**Comment by Zo3i** [comment]
> 不好意思 ，又有新的问题，
> 在后台可以查看到连接成功，但却依然无法访问。服务器是国内的阿里云，这个会有影响吗？
> ![image](https://user-images.githubusercontent.com/16147110/65311223-84395900-dbc2-11e9-958f-61d915483b89.png)
> ![image](https://user-images.githubusercontent.com/16147110/65311278-9adfb000-dbc2-11e9-9ea1-bfcc7ae1604a.png)
> ![image](https://user-images.githubusercontent.com/16147110/65311298-a16e2780-dbc2-11e9-8c7f-56b06e8d56ec.png)

可能是服务器端口没开。

**Comment by luisxin** [comment]
> > 不好意思 ，又有新的问题，
> > 在后台可以查看到连接成功，但却依然无法访问。服务器是国内的阿里云，这个会有影响吗？
> > ![image](https://user-images.githubusercontent.com/16147110/65311223-84395900-dbc2-11e9-958f-61d915483b89.png)
> > ![image](https://user-images.githubusercontent.com/16147110/65311278-9adfb000-dbc2-11e9-9ea1-bfcc7ae1604a.png)
> > ![image](https://user-images.githubusercontent.com/16147110/65311298-a16e2780-dbc2-11e9-8c7f-56b06e8d56ec.png)
> 
> 可能是服务器端口没开。
是7000端口吗？都已经设置妥当 了
![image](https://user-images.githubusercontent.com/16147110/65317574-b3ee5e00-dbce-11e9-920e-0f6fa39ddf4e.png)
![image](https://user-images.githubusercontent.com/16147110/65317613-c5376a80-dbce-11e9-9b69-158b7bd3cc60.png)

**Comment by luisxin** [comment]
![image](https://user-images.githubusercontent.com/16147110/65317698-eb5d0a80-dbce-11e9-93d4-0b74bf8c2659.png)

**Comment by Zo3i** [comment]
你的用处是什么。web穿透吗。

**Comment by Zo3i** [comment]
我刚刚登上你的frpMgr测试了一下。是没问题的。你是访问地址错了。
本地：80 - > 转发到 服务器 8080 
所以你应该访问xxx.你的域名:8080
---
最后提醒你一下你的IP域名泄露了。赶紧编辑掉

**Comment by luisxin** [comment]
感谢回复，换了个IP和端口，依然不行啊。
![image](https://user-images.githubusercontent.com/16147110/65367370-0d07d180-dc63-11e9-941a-28b238ed95eb.png)、
![image](https://user-images.githubusercontent.com/16147110/65367375-17c26680-dc63-11e9-9ce8-a3cbc4f3a353.png)

![image](https://user-images.githubusercontent.com/16147110/65367372-1133ef00-dc63-11e9-9142-76ca6f128889.png)

**Comment by Zo3i** [comment]
老哥是不是应该提升一下阅读理解能力，是访问luis.betteru.cc:8080这个网址啊。

**Comment by luisxin** [comment]
> 老哥是不是应该提升一下阅读理解能力，是访问luis.betteru.cc:8080这个网址啊。

我错了。。只是因为我把frp_server这个地方的商品改成80了，所以说，如果我想使用luis.betteru.cc：80进行访问的话，在此处设置是无效的了？
![image](https://user-images.githubusercontent.com/16147110/65368019-02523a00-dc6d-11e9-935b-594121e2e95d.png)

**Comment by Zo3i** [comment]
我没看到你改成80端口了，你改了80端口服务端应该重新安装。。我没有试过这样行不行。你可以试试。
