### ISSUE TITLE
问一下是否支持armbian

### ISSUE THREAD

**Issue by wulaca** [Zo3i/frpMgr#11]
在moerats.com接触到此项目，可视化做的很棒，下载的文件支持mac 和win

**Comment by Zo3i** [comment]
你可以去看看原生的frp支不支持，如果可以的话，我这边大概可以添加上这个功能。

**Comment by wulaca** [comment]
我看到原生frp是支持的，如果能加上！十分感谢！！

**Comment by Zo3i** [comment]
你是做web开发吗
