### ISSUE TITLE
重新编译的时候缺少com.hk.itg:client-trader:jar:0.01这个jar包

### ISSUE THREAD

**Issue by 521chy** [Zo3i/frpMgr#14]
重新编译的时候缺少com.hk.itg:client-trader:jar:0.01 这个包。maven过去不。。

**Comment by Zo3i** [comment]
<dependency>
    <groupId>com.hk.itg</groupId>
    <artifactId>client-trader</artifactId>
    <version>0.0.1-SNAPSHOT</version>
 </dependency>

删除这个包就行了。。

**Comment by 521chy** [comment]
好吧
