### ISSUE TITLE
远程服务器安装怎么指定ssh端口号呢

### ISSUE THREAD

**Issue by 521chy** [Zo3i/frpMgr#15]
远程服务器安装怎么指定ssh端口号呢?  

服务器IP:8812这样不行

建议，远程安装失败的话，单独生成一个sh脚本显示在窗口，提示自行登录服务器操作。

**Comment by Zo3i** [comment]
现在默认的都是22端口。面向小白用户，所以没有那么多参数需要自定义。

**Comment by 521chy** [comment]
了解啦。刚好卡在了比小白强没多少的状态，看样子得试试读源码了吧

**Comment by Zo3i** [comment]
很简单的，加个字段就好了。
