### ISSUE TITLE
远程安装的FRP是那个版本，客户端是linux，提供下载的客户端只有mac和win，github下载来0.31.2的frpc执行没反应，请问有什么办法可以解决呢。

### ISSUE THREAD

**Issue by pgfeng** [Zo3i/frpMgr#16]

**Comment by Zo3i** [comment]
抱歉，暂时没有linux客户端的版本。因为可视化操作是针对小白的。如果你懂linux操作建议还是手动操作。

**Comment by pgfeng** [comment]
> ## 抱歉，暂时没有linux客户端的版本。因为可视化操作是针对小白的。如果你懂linux操作建议还是手动操作。
> frp 用的版本是0.24.0

好的，谢谢。
