### ISSUE TITLE
使用一键安装脚本出现404

### ISSUE THREAD

**Issue by xiyan123** [Zo3i/frpMgr#18]
大佬，使用一键安装脚本出现404怎么解决啊

一开始是使用一键脚本因为没有安装java，所以没跑起来apache，后来装了个java跑起来了apache但是访问网页是404。

**Comment by xiyan123** [comment]
我看了一下，在docker里，没有找到frp，无论是文件还是目录，网站资源应该是依托frp.jar吧，但是docker容器内并没有frp.jar

**Comment by Zo3i** [comment]
你直接执行脚本就行了。只要docker 环境就行了。不用java什么的。
