### ISSUE TITLE
可以不使用docker直接运行吗

### ISSUE THREAD

**Issue by cnluminous** [Zo3i/frpMgr#26]
可以不使用docker直接运行吗？宝塔面板安装一直报错,希望能使用宝塔插件java项目部署工具直接部署到系统

**Comment by cnluminous** [comment]
或者有没有什么脚本可以直接运行

**Comment by Zo3i** [comment]
wget -O - https://raw.githubusercontent.com/Zo3i/OCS/master/docker/docker-all2.sh | sh
wget -O - https://raw.githubusercontent.com/Zo3i/frpMgr/master/web/src/main/docker/final/run.sh | sh

这两句一起运行就可以了啊

**Comment by cnluminous** [comment]
执行后一直报错，无法启用，方便加下qq吗？2179089490

**Comment by Zo3i** [comment]
报错截图发出来看看

**Comment by cnluminous** [comment]
![QQ截图20200827133558](https://user-images.githubusercontent.com/47070284/91388931-e686e900-e86a-11ea-9865-27b5752cb340.png)

**Comment by Zo3i** [comment]
加你了

**Comment by likujy2061** [comment]
你好，大佬，你们脚本下载地址失败了了！是不是服务挂掉了。
![image](https://user-images.githubusercontent.com/26838977/91537130-620a9800-e948-11ea-8d28-ad1090a1e805.png)

**Comment by Zo3i** [comment]
可能是因为你是国内服务器

**Comment by likujy2061** [comment]
感谢！我确实是国内服务器！！！！！！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Zo3i/frpMgr"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月28日(星期五) 下午4:18
收件人:&nbsp;"Zo3i/frpMgr"<frpMgr@noreply.github.com&gt;;
抄送:&nbsp;"1405161366"<1405161366@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Zo3i/frpMgr] 可以不使用docker直接运行吗 (#26)





 
可能是因为你是国内服务器

**Comment by likujy2061** [comment]
肯定是可以的啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Zo3i/frpMgr"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月3日(星期四) 上午8:48
收件人:&nbsp;"Zo3i/frpMgr"<frpMgr@noreply.github.com&gt;;
抄送:&nbsp;"1405161366"<1405161366@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Zo3i/frpMgr] 可以不使用docker直接运行吗 (#26)





 
Closed #26.

**Comment by Botium1** [comment]
> wget -O - https://raw.githubusercontent.com/Zo3i/OCS/master/docker/docker-all2.sh | sh wget -O - https://raw.githubusercontent.com/Zo3i/frpMgr/master/web/src/main/docker/final/run.sh | sh
> 
> 这两句一起运行就可以了啊

这两句还是用了docker啊。。
