### ISSUE TITLE
centos7 服务重启之后，docker-composer up启动不了

### ISSUE THREAD

**Issue by webwlsong** [Zo3i/frpMgr#27]
centos7服务器重启之后
按照issues中回复的
在frpMgr/web/src/main/docker/final   执行 docker-compose down   docker-compose up

页面一直

frp_1    | 2020-08-31 23:18:00.334 INFO  ExceptionHandlerExceptionResolver - Detected @ExceptionHandler methods in adviceController
frp_1    | 2020-08-31 23:18:00.472 DEBUG BeetlUtils - Loading beetl config: [classpath:/config/beetl-core.properties, classpath:/config/beetl.properties]
frp_1    | 2020-08-31 23:18:02.122 INFO  AnnotationMBeanExporter - Registering beans for JMX exposure on startup
frp_1    | 2020-08-31 23:18:02.162 INFO  Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8999"]
frp_1    | 2020-08-31 23:18:02.183 INFO  Http11NioProtocol - Starting ProtocolHandler ["http-nio-8999"]
frp_1    | 2020-08-31 23:18:02.227 INFO  NioSelectorPool - Using a shared selector for servlet write/read
frp_1    | 2020-08-31 23:18:02.376 INFO  TomcatEmbeddedServletContainer - Tomcat started on port(s): 8999 (http)
frp_1    | 2020-08-31 23:18:02.379 INFO  Application - Started Application in 20.555 seconds (JVM running for 22.018)
frp_1    | ========= Enabled refresh mybatis mapper =========

执行不下去了

**Comment by Zo3i** [comment]
这已经是启动成功了。
frpMgr/web/src/main/docker/final 
执行 
```
docker-compose down 
docker-compose up -d 
后台启动即可

**Comment by webwlsong** [comment]
到了这个界面，不要要等待很长时间。才能访问

**Comment by Zo3i** [comment]
可能是你服务器网络不太好。一般国外服务器都安装很快的
