### ISSUE TITLE
本软件和mysql的问题

### ISSUE THREAD

**Issue by DUWENINK** [Zo3i/frpMgr#3]
如果我用宝塔安装mysql之后,用了您的脚本之后,尝试在docker内拉起mysql,但是把mysql的默认端口映射到外网的时候,并没有检查外网的端口是否已经被占用,因此抛出了如下错误:

` Creating network "final_default" with the default driver
Creating final_mysql_1 ... error

ERROR: for final_mysql_1  Cannot start service mysql: b'driver failed programming external connectivity on endpoint final_mysql_1 (765e6cd700ed1f077949966a791c57910dac546810214e809734b2ae8df04d38): Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use'

ERROR: for mysql  Cannot start service mysql: b'driver failed programming external connectivity on endpoint final_mysql_1 (765e6cd700ed1f077949966a791c57910dac546810214e809734b2ae8df04d38): Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use'
ERROR: Encountered errors while bringing up the project. `

#建议的解决方案为:# 
` wget -O - https://raw.githubusercontent.com/Zo3i/frpMgr/master/web/src/main/docker/final/run.sh | sh -p 23306 `可以指定端口

**Comment by Zo3i** [comment]
感谢提醒，已修复bug。修改docker-compose.yml 的端口配置即可绑定docker:3306端口到宿主机器的任意端口。
