### ISSUE TITLE
一键部署运行报错

### ISSUE THREAD

**Issue by ZeroSpider6** [Zo3i/frpMgr#39]
docker-compose up -d
mysql容器运行正常
frp容器一直restarting，log信息为:no such file …

**Comment by Zo3i** [comment]
我刚刚试了，没有问题。直接跑脚本就行。 
wget -O - https://raw.githubusercontent.com/Zo3i/frpMgr/master/web/src/main/docker/final/run.sh | sh

你是不是有啥操作。具体log是什么。

**Comment by AnsonLuo** [comment]
![image](https://user-images.githubusercontent.com/20241489/148568309-d20a1da1-4181-4f62-b165-755a455d7acc.png)

**Comment by Zo3i** [comment]
![image](https://user-images.githubusercontent.com/30296801/148629260-5d79f76f-fd14-406b-bd9a-de4a675a4a86.png)
对比看看你有没有少了文件。实在不行，就删了重新跑下文档里面写的脚本。

**Comment by ZeroSpider6** [comment]
删掉重新跑成功了，谢谢
