### ISSUE TITLE
我的服务器SSH端口不是22，导致远程安装失败，怎么解？

### ISSUE THREAD

**Issue by thofd** [Zo3i/frpMgr#5]
我的服务器SSH端口不是22，导致远程安装失败，怎么解？

**Comment by Zo3i** [comment]
设计的时候，默认是22. 如果有需求，可以添加这个字段。

**Comment by thofd** [comment]
没想到大侠这么快回复了，明白了，也就是说目前只能改成22先用，其实也没有特别用途，只是说这样安全一点

**Comment by Zo3i** [comment]
有时间会加上这个功能，周末不想打开电脑哈哈哈。
