### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by uitsrt** [Zo3i/frpMgr#50]
root@ip-172-26-3-43:~/frpMgr/web/src/main/docker/final# docker-compose up -d
[+] Building 1.0s (3/3) FINISHED                                                                            
 => [internal] load build definition from Dockerfile                                                   0.0s
 => => transferring dockerfile: 32B                                                                    0.0s
 => [internal] load .dockerignore                                                                      0.0s
 => => transferring context: 2B                                                                        0.0s
 => ERROR [internal] load metadata for docker.io/library/java:8                                        0.9s
------
 > [internal] load metadata for docker.io/library/java:8:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: docker.io/library/java:8: not found

**Comment by Zo3i** [comment]
可能是你的docker安装的有问题。我的建议是帖截图。你这个代码格式不好看。
